# Generated by Django 2.2.5 on 2019-11-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='color',
            field=models.CharField(default='Blanco', max_length=50),
        ),
    ]
