# Generated by Django 2.2.5 on 2019-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_coche_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
