# Generated by Django 2.2.5 on 2019-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20191127_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/Marcas/'),
        ),
    ]
