# Generated by Django 2.2.5 on 2019-11-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20191127_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='taller_id',
        ),
        migrations.AddField(
            model_name='marca',
            name='taller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Taller'),
        ),
    ]
