# Generated by Django 2.2.5 on 2019-11-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente')),
                ('coche_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Coche')),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Empleado')),
            ],
        ),
    ]
