# Generated by Django 2.2.5 on 2019-11-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Proveedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente')),
                ('coche_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Coche')),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Empleado')),
            ],
        ),
    ]
